### ISSUE TITLE
Nutrition parsing breaks on "<" symbol

### ISSUE THREAD

**Issue by ricktav** [rkalis/AppiePy#10]
This breaks:

```
from appiepy import Product

print(Product("/producten/product/wi420790/princes-tonijn-stukken-in-water").nutrition)
```

**error: xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 211**

I traced it back to an less than character in the nutrition table. (Koolhydraten < 0.1)

**Comment by rkalis** [comment]
This was fixed by @ricktav in #11
